# This is a basic workflow to help you get started with Actions

name: ki_devops3_test

# Controls when the action will run. 
on:
  
  #push:
    # Triggers the workflow on push events for the branches start with release
    #branches:: [ 'release/**' ]

    # Triggers the workflow on push events but only for the master branch
    #branches: [ master ]

    # Triggers the workflow on push tag
    #tags: ['*']
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "devops3_test"
  devops3_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run test
        run: |
           set -e
           echo call ./Publish/DevOps3/build-bash/10.Test.bash to test

           cd ./Publish/DevOps3/build-bash
           bash 10.Test.bash;
           echo run test succeed!
